src/objects/Contact__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Адреса</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientName__c</fullName>
        <label>Телефон</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Коментар</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeneralDiscount__c</fullName>
        <label>Спеціальні умови</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>2 %</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 %</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 %</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 %</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6 %</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7 %</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>8 %</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10 %</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13 %</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14 %</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15 %</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Контакт</label>
    <nameField>
        <label>Ім&apos;я</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Контакти</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Curtain__c.object
<CustomObject>
    <fields>
        <fullName>CarnizWigth__c</fullName>
        <label>Ширина Карнізу (см)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carniz__c</fullName>
        <label>Карніз</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>gardinia</fullName>
                    <label>Gardinia</label>
                </value>
                <value>
                    <fullName>alutat</fullName>
                    <label>Alutat</label>
                </value>
                <value>
                    <fullName>ks</fullName>
                    <label>KS</label>
                </value>
                <value>
                    <fullName>lux</fullName>
                    <label>Lux S-M</label>
                </value>
                <value>
                    <fullName>ds</fullName>
                    <label>DS</label>
                </value>
                <value>
                    <fullName>circle</fullName>
                    <label>Круглий</label>
                </value>
                <value>
                    <fullName>metal</fullName>
                    <label>Металічний П-обр крючок</label>
                </value>
                <value>
                    <fullName>other</fullName>
                    <label>Інший</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Контакт</label>
        <referenceTo>Contact__c</referenceTo>
        <relationshipLabel>Curtains</relationshipLabel>
        <relationshipName>Curtains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Diameter__c</fullName>
        <label>Діаметр Карнізу</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>2 см</label>
                </value>
                <value>
                    <fullName>2_5</fullName>
                    <label>2,5 см</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 см</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HeightPoint__c</fullName>
        <label>Точка Висоти</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>do_carnizu</fullName>
                    <label>до карнізу</label>
                </value>
                <value>
                    <fullName>do_gachka</fullName>
                    <label>до гачка</label>
                </value>
                <value>
                    <fullName>do_petli</fullName>
                    <label>до петлі</label>
                </value>
                <value>
                    <fullName>do_virobu</fullName>
                    <label>готового виробу</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Висота (см)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Назва</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nisha__c</fullName>
        <label>Ніша</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>yes</fullName>
                    <label>Так</label>
                </value>
                <value>
                    <fullName>no</fullName>
                    <label>Ні</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PriceType__c</fullName>
        <label>Валюта</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>грн</fullName>
                    <label>грн.</label>
                </value>
                <value>
                    <fullName>уо</fullName>
                    <label>опт, у.о.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Ціна тканини</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Кількість</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 штука</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 штуки</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 штуки</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <label>Кімната</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TasmaPrice__c</fullName>
        <label>Ціна тасьми</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>85</fullName>
                    <label>85 грн.</label>
                </value>
                <value>
                    <fullName>110</fullName>
                    <label>110 грн.</label>
                </value>
                <value>
                    <fullName>140</fullName>
                    <label>140 грн.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tasma__c</fullName>
        <label>Тасьма</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>fixProzora</fullName>
                    <label>Прозора фіксована</label>
                </value>
                <value>
                    <fullName>fixHB</fullName>
                    <label>ХБ фіксована</label>
                </value>
                <value>
                    <fullName>notfix</fullName>
                    <label>Не фіксована</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Тип</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>shtora</fullName>
                    <label>Штора</label>
                </value>
                <value>
                    <fullName>tul</fullName>
                    <label>Тюль</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zbirka__c</fullName>
        <label>Збірка</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>enigma_15</fullName>
                    <label>Enigma 1:1,5</label>
                </value>
                <value>
                    <fullName>enigma_18</fullName>
                    <label>Enigma 1:1,8</label>
                </value>
                <value>
                    <fullName>enigma_2</fullName>
                    <label>Enigma 1:2</label>
                </value>
                <value>
                    <fullName>enigma_25</fullName>
                    <label>Enigma 1:2,5</label>
                </value>
                <value>
                    <fullName>enigma_3</fullName>
                    <label>Enigma 1:3</label>
                </value>
                <value>
                    <fullName>sofora_18</fullName>
                    <label>Sofora 1:1,8</label>
                </value>
                <value>
                    <fullName>sofora_2</fullName>
                    <label>Sofora 1:2</label>
                </value>
                <value>
                    <fullName>pinella</fullName>
                    <label>Pinella</label>
                </value>
                <value>
                    <fullName>hvulya</fullName>
                    <label>Хвиля 1:2</label>
                </value>
                <value>
                    <fullName>luversna</fullName>
                    <label>Люверсна</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Штора</label>
    <nameField>
        <label>Штора Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Штори</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Curtain__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Коментар</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/curtainFormController.cls
/**
 * Created by Kostiantyn_Marchenko on 12/2/2024.
 */

public with sharing class curtainFormController {
    
    @AuraEnabled
    public static void createContact(String jsonDataFromForm) {
        System.debug('jsonDataFromForm ' + jsonDataFromForm);
        try {
            Map<String, Object> dataFromForm = (Map<String, Object>) JSON.deserializeUntyped(jsonDataFromForm);
            
            List<Contact__c> contacts = new List<Contact__c>();
            
            String name = (String) ((Map<String, Object>) dataFromForm.get('clientData')).get('name');
            String phone = (String) ((Map<String, Object>) dataFromForm.get('clientData')).get('phone');
            String discount = (String) ((Map<String, Object>) dataFromForm.get('clientData')).get('discount');
            String description = (String) ((Map<String, Object>) dataFromForm.get('clientData')).get('descrioption');
            String address = (String) ((Map<String, Object>) dataFromForm.get('clientData')).get('address');
            System.debug('phone ' + phone);
            List<Contact__c> existingContacts = [
                    SELECT Id, Name,ClientName__c, Description__c, GeneralDiscount__c, Address__c
                    FROM Contact__c
                    WHERE Name = :phone
                    LIMIT 1
            ];
            System.debug('existingContact ' + existingContacts);
            if (!existingContacts.isEmpty()) {
                existingContacts[0].ClientName__c = name;
                existingContacts[0].Description__c += (description != null ? '; ' + description : '');
                existingContacts[0].GeneralDiscount__c = discount;
                existingContacts[0].Address__c = address;
                
                update existingContacts;
                
                contacts.add(existingContacts[0]);
            } else {
                Contact__c newContact = new Contact__c();
                newContact.ClientName__c = name;
                newContact.Name = phone;
                newContact.GeneralDiscount__c = discount;
                newContact.Description__c = description;
                newContact.Address__c = address;
                
                Database.insert(newContact);
                
                contacts.add(newContact);
                System.debug(newContact);
            }
            
            List<Object> blocks = (List<Object>) dataFromForm.get('blocks');
            
            List<Curtain__c> curtains = new List<Curtain__c>();
            for (Contact__c contact : contacts) {
                for (Object blockObj : blocks) {
                    Map<String, Object> block = (Map<String, Object>) blockObj;
                    System.debug('Block: ' + JSON.serializePretty(block));
                    System.debug((String) block.get('label'));
                    Curtain__c curtain = new Curtain__c(
                            Room__c = (String) block.get('room'),
                            Type__c = (String) block.get('type'),
                            Quantity__c = String.isBlank((String)block.get('quantity')) ? '1' : (String)block.get('quantity'),
                            Name__c = (String) block.get('label'),
                            Price__c = (String) block.get('price'),
                            PriceType__c =  String.isBlank((String) block.get('priceType')) ? 'грн.' : (String) block.get('priceType'),
                            Nisha__c = (String) block.get('nisha'),
                            Carniz__c = (String) block.get('carniz'),
                            Diameter__c = (String) block.get('diameter'),
                            CarnizWigth__c = (String) block.get('carniz_wigth'),
                            HeightPoint__c = (String) block.get('heightPoint'),
                            Height__c = (String) block.get('height'),
                            Tasma__c = (String) block.get('tasma'),
                            Zbirka__c = (String) block.get('zbirka'),
                            TasmaPrice__c = (String) block.get('tasmaPrice'),
                            PoshivPrice__c = (String) block.get('poshiv'),
                            Delivery__c = (String) block.get('delivery'),
                            DeliveryNumber__c = (String) block.get('deliveryNumber'),
                            NavisPrice__c = (String) block.get('navisPrice'),
                            Navis__c = (Boolean) block.get('navis'),
                            Viizd__c = (Boolean) block.get('viizd'),
                            CustomWigth__c = (String) block.get('custom_wigth'),
                            CurtainDiscount__c = (String) block.get('curtainDiscount'),
                            Contact__c = contact.Id
                    );
                    
                    curtains.add(curtain);
                    System.debug('Curtains ' + curtains);
                
                }
            }
            
            insert curtains;
            
            System.debug('Curtains ' + curtains);
            CurtainCalculator.calculateData(curtains[0]);
            update curtains;
        } catch (Exception ex) {
            System.debug(ex);
        }
    }
}