src/objects/Contact__c.object
<CustomObject>
    <fields>
        <fullName>GeneralDiscount__c</fullName>
        <label>Спеціальні умови</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>2 %</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 %</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 %</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 %</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6 %</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7 %</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>8 %</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10 %</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13 %</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14 %</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15 %</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Контакт</label>
    <nameField>
        <label>Ім&apos;я</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Контакти</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Curtain__c.object
<CustomObject>
    <fields>
        <fullName>CarnizWigth__c</fullName>
        <label>Ширина Карнізу (см)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Контакт</label>
        <referenceTo>Contact__c</referenceTo>
        <relationshipLabel>Curtains</relationshipLabel>
        <relationshipName>Curtains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CurtainPriceSum__c</fullName>
        <label>Ціна за тканину</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomWigth__c</fullName>
        <label>Ширина тканини (см)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeliveryNumber__c</fullName>
        <label>Кількість доставок</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery__c</fullName>
        <label>Доставка</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>120</fullName>
                    <label>120 грн.</label>
                </value>
                <value>
                    <fullName>150</fullName>
                    <label>150 грн.</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <label>180 грн.</label>
                </value>
                <value>
                    <fullName>200</fullName>
                    <label>200 грн.</label>
                </value>
                <value>
                    <fullName>220</fullName>
                    <label>220 грн.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ManualPrice__c</fullName>
        <label>Відома ціна</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MeterageNaPoshiv__c</fullName>
        <label>Метраж на пошив</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meterage__c</fullName>
        <label>Метраж тканини</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NavisPriceSum__c</fullName>
        <label>Ціна за навіс</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NavisPrice__c</fullName>
        <label>Ціна навісу</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>120</fullName>
                    <label>120 грн м.п.</label>
                </value>
                <value>
                    <fullName>140</fullName>
                    <label>140 грн. м.п.</label>
                </value>
                <value>
                    <fullName>160</fullName>
                    <label>160 грн. м.п.</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <label>180 грн. м.п.</label>
                </value>
                <value>
                    <fullName>200</fullName>
                    <label>200 грн. м.п.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Navis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Навіс</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PoshivPriceSum__c</fullName>
        <label>Ціна за пошив</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PoshivPrice__c</fullName>
        <label>Ціна пошиву</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>150</fullName>
                    <label>150 грн.</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <label>180 грн.</label>
                </value>
                <value>
                    <fullName>200</fullName>
                    <label>200 грн.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Ціна тканини</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Кількість</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 штука</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 штуки</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 штуки</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TasmaMetrage__c</fullName>
        <label>Метраж тасьми</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TasmaPriceSum__c</fullName>
        <label>Ціна за тасьму</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TasmaPrice__c</fullName>
        <label>Ціна тасьми</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>85</fullName>
                    <label>85 грн.</label>
                </value>
                <value>
                    <fullName>110</fullName>
                    <label>110 грн.</label>
                </value>
                <value>
                    <fullName>140</fullName>
                    <label>140 грн.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Viizd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Виїзд</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zbirka__c</fullName>
        <label>Збірка</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>enigma_15</fullName>
                    <label>Enigma 1:1,5</label>
                </value>
                <value>
                    <fullName>enigma_18</fullName>
                    <label>Enigma 1:1,8</label>
                </value>
                <value>
                    <fullName>enigma_2</fullName>
                    <label>Enigma 1:2</label>
                </value>
                <value>
                    <fullName>enigma_25</fullName>
                    <label>Enigma 1:2,5</label>
                </value>
                <value>
                    <fullName>enigma_3</fullName>
                    <label>Enigma 1:3</label>
                </value>
                <value>
                    <fullName>sofora_18</fullName>
                    <label>Sofora 1:1,8</label>
                </value>
                <value>
                    <fullName>sofora_2</fullName>
                    <label>Sofora 1:2</label>
                </value>
                <value>
                    <fullName>pinella</fullName>
                    <label>Pinella</label>
                </value>
                <value>
                    <fullName>hvulya</fullName>
                    <label>Хвиля 1:2</label>
                </value>
                <value>
                    <fullName>luversna</fullName>
                    <label>Люверсна</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Штора</label>
    <nameField>
        <label>Штора Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Штори</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CurtainCalculator.cls
/**
 * Created by Kostiantyn_Marchenko on 2/24/2025.
 */

public with sharing class CurtainCalculator {
    
    public final static Decimal NAVIS_PRICE = 500;
    
    public static List<Curtain__c> calculateData(List<Curtain__c> curtainObjects) {
        
        List<Curtain__c> curtainToWork = new List<Curtain__c>();
        for (Curtain__c curtainObject : curtainObjects) {
            
            Contact__c parentContact = new Contact__c();
            if (!String.isBlank(curtainObject.Contact__c)) {
                parentContact = [
                        SELECT GeneralDiscount__c
                        FROM Contact__c
                        WHERE Id = :curtainObject.Contact__c
                ];
            }
            
            
            if (curtainObject.ManualPrice__c == null) {
                
                String quantity;
                if (curtainObject.Quantity__c != null) {
                    quantity = curtainObject.Quantity__c;
                } else {
                    quantity = '1';
                    curtainObject.Quantity__c = quantity;
                }
                
                if (!String.isBlank(curtainObject.CustomWigth__c)) {
                    Decimal rawMeterage =
                            ((Decimal.valueOf(curtainObject.CustomWigth__c) / 100));
                    
                    // Округление Meterage__c в большую сторону до одного знака после запятой
                    curtainObject.Meterage__c = String.valueOf(rawMeterage.setScale(1, System.RoundingMode.UP));
                } else if (!String.isBlank(curtainObject.CarnizWigth__c)) {
                    Decimal rawMeterage =
                            ((Decimal.valueOf(curtainObject.CarnizWigth__c) * ZBIRKA_VALUES.get(curtainObject.Zbirka__c)) / 100) +
                            (Decimal.valueOf(quantity) * 0.1);
                    
                    // Округление Meterage__c в большую сторону до одного знака после запятой
                    curtainObject.Meterage__c = String.valueOf(rawMeterage.setScale(1, System.RoundingMode.UP));
                }

//                System.debug('curtainObject.Meterage__c ' + curtainObject.Meterage__c);

// Округление MeterageNaPoshiv__c по методу roundMeterage
                if (!String.isBlank(curtainObject.Meterage__c)) {
                    curtainObject.MeterageNaPoshiv__c = String.valueOf(roundMeterage(Decimal.valueOf(curtainObject.Meterage__c)));
                    System.debug('curtainObject.MeterageNaPoshiv__c ' + curtainObject.MeterageNaPoshiv__c);
                    
                    
                    curtainObject.CurtainPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.Meterage__c) *
                            Decimal.valueOf(curtainObject.Price__c));
                    System.debug('curtainObject.CurtainPriceSum__c ' + curtainObject.CurtainPriceSum__c);
                    
                    curtainObject.TasmaMetrage__c = String.valueOf(roundMeterage(
                            (Decimal.valueOf(curtainObject.Meterage__c) + (Decimal.valueOf(quantity) * 0.1))
                    ));
                    System.debug('curtainObject.TasmaMetrage__c ' + curtainObject.TasmaMetrage__c);
                    
                    curtainObject.TasmaPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.TasmaMetrage__c) *
                            Decimal.valueOf(curtainObject.TasmaPrice__c));
                    System.debug('curtainObject.TasmaPriceSum__c ' + curtainObject.TasmaPriceSum__c);
                    
                    curtainObject.PoshivPriceSum__c = '';
                    if(String.isNotBlank(curtainObject.PoshivPrice__c)) {
                        curtainObject.PoshivPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.Meterage__c) *
                                Decimal.valueOf(curtainObject.PoshivPrice__c));
                        System.debug('curtainObject.PoshivPriceSum__c ' + curtainObject.PoshivPriceSum__c);
                    }
                    
                    
                    if (curtainObject.Navis__c) {
                        if (curtainObject.Viizd__c) {
                            curtainObject.NavisPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.Meterage__c) *
                                    Decimal.valueOf(curtainObject.NavisPrice__c) + NAVIS_PRICE);
                        } else {
                            curtainObject.NavisPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.Meterage__c) *
                                    Decimal.valueOf(curtainObject.NavisPrice__c));
                        }
                    }
                }
                System.debug('curtainObject.NavisPriceSum__c ' + curtainObject.NavisPriceSum__c);
                
                /*if (curtainObject.ManualPrice__c == null) {
                    
                    String quantity;
                    if (!String.isBlank(curtainObject.Quantity__c)) {
                        quantity = curtainObject.Quantity__c;
                    } else {
                        quantity = '1';
                    }
                    
                    // Проверяем на пустое значение CustomWigth__c, если пустое - оставляем пустым Meterage__c
                    if (!String.isBlank(curtainObject.CustomWigth__c)) {
                        Decimal rawMeterage =
                                ((Decimal.valueOf(curtainObject.CustomWigth__c) * ZBIRKA_VALUES.get(curtainObject.Zbirka__c)) / 100) +
                                (Decimal.valueOf(quantity) * 0.1);
                        
                        // Округление Meterage__c в большую сторону до одного знака после запятой
                        curtainObject.Meterage__c = String.valueOf(rawMeterage.setScale(1, System.RoundingMode.UP));
                    } else {
                        // Если CustomWigth__c пустое, оставляем Meterage__c пустым
                        curtainObject.Meterage__c = null;
                    }
                    
                    System.debug('curtainObject.Meterage__c ' + curtainObject.Meterage__c);
                    
                    // Если Meterage__c пустое, оставляем MeterageNaPoshiv__c пустым
                    if (!String.isBlank(curtainObject.Meterage__c)) {
                        // Округление MeterageNaPoshiv__c по методу roundMeterage
                        curtainObject.MeterageNaPoshiv__c = String.valueOf(roundMeterage(Decimal.valueOf(curtainObject.Meterage__c)));
                        System.debug('curtainObject.MeterageNaPoshiv__c ' + curtainObject.MeterageNaPoshiv__c);
                    } else {
                        curtainObject.MeterageNaPoshiv__c = null;
                    }
                    
                    // Проверка на пустое значение Price__c, если пустое - CurtainPriceSum__c остается пустым
                    if (!String.isBlank(curtainObject.Meterage__c) && !String.isBlank(curtainObject.Price__c)) {
                        curtainObject.CurtainPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.Meterage__c) *
                                Decimal.valueOf(curtainObject.Price__c));
                        System.debug('curtainObject.CurtainPriceSum__c ' + curtainObject.CurtainPriceSum__c);
                    } else {
                        curtainObject.CurtainPriceSum__c = null;
                    }
                    
                    // Проверка на пустое значение TasmaPrice__c, если пустое - TasmaPriceSum__c остается пустым
                    if (!String.isBlank(curtainObject.TasmaMetrage__c) && !String.isBlank(curtainObject.TasmaPrice__c)) {
                        curtainObject.TasmaPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.TasmaMetrage__c) *
                                Decimal.valueOf(curtainObject.TasmaPrice__c));
                        System.debug('curtainObject.TasmaPriceSum__c ' + curtainObject.TasmaPriceSum__c);
                    } else {
                        curtainObject.TasmaPriceSum__c = null;
                    }
                    
                    // Проверка на пустое значение PoshivPrice__c, если пустое - PoshivPriceSum__c остается пустым
                    if (!String.isBlank(curtainObject.Meterage__c) && !String.isBlank(curtainObject.PoshivPrice__c)) {
                        curtainObject.PoshivPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.Meterage__c) *
                                Decimal.valueOf(curtainObject.PoshivPrice__c));
                        System.debug('curtainObject.PoshivPriceSum__c ' + curtainObject.PoshivPriceSum__c);
                    } else {
                        curtainObject.PoshivPriceSum__c = null;
                    }
                    
                    // Проверка на пустое значение NavisPrice__c и Viizd__c
                    if (curtainObject.Navis__c) {
                        if (curtainObject.Viizd__c) {
                            if (!String.isBlank(curtainObject.NavisPrice__c)) {
                                curtainObject.NavisPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.Meterage__c) *
                                        Decimal.valueOf(curtainObject.NavisPrice__c) + 500);
                            } else {
                                curtainObject.NavisPriceSum__c = null;
                            }
                        } else {
                            if (!String.isBlank(curtainObject.NavisPrice__c)) {
                                curtainObject.NavisPriceSum__c = String.valueOf(Decimal.valueOf(curtainObject.Meterage__c) *
                                        Decimal.valueOf(curtainObject.NavisPrice__c));
                            } else {
                                curtainObject.NavisPriceSum__c = null;
                            }
                        }
                    } else {
                        curtainObject.NavisPriceSum__c = null;
                    }
                    System.debug('curtainObject.NavisPriceSum__c ' + curtainObject.NavisPriceSum__c);
                    */
                
                
                Decimal deliveryPrice;
                if (!String.isBlank(curtainObject.Delivery__c)) {
                    if (!String.isBlank(curtainObject.DeliveryNumber__c)) {
                        deliveryPrice = Decimal.valueOf(curtainObject.Delivery__c) * Decimal.valueOf(curtainObject.DeliveryNumber__c);
                    } else {
                        deliveryPrice = Decimal.valueOf(curtainObject.Delivery__c);
                    }
                
                }
                
                Decimal finalPrice = 0;
                System.debug('CurtainPriceSum__c: ' + curtainObject.CurtainPriceSum__c);
                System.debug('TasmaPriceSum__c: ' + curtainObject.TasmaPriceSum__c);
                System.debug('PoshivPriceSum__c: ' + curtainObject.PoshivPriceSum__c);
                System.debug('NavisPriceSum__c: ' + curtainObject.NavisPriceSum__c);
                System.debug('Delivery__c: ' + curtainObject.Delivery__c);
                System.debug('DeliveryNumber__c: ' + curtainObject.DeliveryNumber__c);
                
                finalPrice += !String.isBlank(curtainObject.CurtainPriceSum__c) ? extractDecimal(curtainObject.CurtainPriceSum__c) : 0;
                finalPrice += !String.isBlank(curtainObject.TasmaPriceSum__c) ? extractDecimal(curtainObject.TasmaPriceSum__c) : 0;
                finalPrice += !String.isBlank(curtainObject.PoshivPriceSum__c) ? extractDecimal(curtainObject.PoshivPriceSum__c) : 0;
                finalPrice += !String.isBlank(curtainObject.NavisPriceSum__c) ? extractDecimal(curtainObject.NavisPriceSum__c) : 0;
                finalPrice += !String.isBlank(curtainObject.Delivery__c) && !String.isBlank(curtainObject.DeliveryNumber__c) ?
                        Decimal.valueOf(curtainObject.Delivery__c) * Decimal.valueOf(curtainObject.DeliveryNumber__c) : 0;
                
                
                if (!String.isBlank(curtainObject.CurtainDiscount__c) ||
                        (parentContact != null && !String.isBlank(parentContact.GeneralDiscount__c))) {
                    Integer discountValue = !String.isBlank(curtainObject.CurtainDiscount__c) ?
                            Integer.valueOf(curtainObject.CurtainDiscount__c) : Integer.valueOf(parentContact.GeneralDiscount__c);
                    
                    if (Math.mod(discountValue, 2) == 0) {
                        finalPrice += (finalPrice * discountValue / 100);
                    } else {
                        finalPrice -= (finalPrice * discountValue / 100);
                    }
                }
                
                curtainObject.GeneralPrice__c = finalPrice;
                curtainToWork.add(curtainObject);
            
            } else {
                Decimal finalPrice = curtainObject.ManualPrice__c;
                if (!String.isBlank(curtainObject.CurtainDiscount__c) ||
                        (parentContact != null && !String.isBlank(parentContact.GeneralDiscount__c))) {
                    Integer discountValue = !String.isBlank(curtainObject.CurtainDiscount__c) ?
                            Integer.valueOf(curtainObject.CurtainDiscount__c) : Integer.valueOf(parentContact.GeneralDiscount__c);
                    
                    if (Math.mod(discountValue, 2) == 0) {
                        finalPrice += (curtainObject.ManualPrice__c * discountValue / 100);
                    } else {
                        finalPrice -= (curtainObject.ManualPrice__c * discountValue / 100);
                    }
                }
                
                curtainObject.GeneralPrice__c = finalPrice;
                
                curtainToWork.add(curtainObject);
            }
            System.debug('curtainObject.FinalPrice__c ' + curtainObject.GeneralPrice__c);

//            curtainToWor curtainObject;
        }
        
        return curtainToWork;
    }
    
    public static final Map<String, Decimal> ZBIRKA_VALUES = new Map<String, Decimal>{
            'Enigma 1:1,5' => 1.5,
            'Enigma 1:1,8' => 1.8,
            'Enigma 1:2' => 2,
            'Enigma 1:2,5' => 2.5,
            'Enigma 1:3' => 3,
            'Sofora 1:1,8' => 1.8,
            'Sofora 1:2' => 2,
            'Pinella' => 1,
            'Хвиля 1:2' => 2,
            'Люверсна' => 2,
            'Глайдерна 1:2 + FES' => 2,
            'Хвиля 1:1,5' => 1.5
    };
    
    public static Decimal extractDecimal(String value) {
        if (value == null || value == '') {
            return 0;
        }
        String numericPart = value.replaceAll('[^0-9.]', ''); // Оставляем только цифры и точку
        System.debug('numericPart ' + numericPart);
        return Decimal.valueOf(numericPart);
    }
    
    public static Decimal roundMeterage(Decimal value) {
        Decimal floored = value.setScale(1, System.RoundingMode.DOWN); // Оставляем 1 знак после запятой
        Decimal fraction = floored - floored.intValue(); // Получаем дробную часть
        
        if (fraction == 0.1 || fraction == 0.2 || fraction == 0.6) {
            return floored; // Не изменяем число
        } else if (fraction == 0.3 || fraction == 0.4 || fraction == 0.5) {
            return floored.intValue() + 0.5; // Округляем к 0.5
        } else if (fraction >= 0.7) {
            return floored.intValue() + 1; // Округляем вверх
        } else {
            return floored; // По умолчанию возвращаем число без изменений
        }
    }

}