src/objects/Contact__c.object
<CustomObject>
    <fields>
        <fullName>FinalPrice__c</fullName>
        <inlineHelpText>Ціна, яку затверджено з покупцем в ході розгляду і затвердження замовлення.</inlineHelpText>
        <label>Фінальна ціна</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GeneralDiscount__c</fullName>
        <label>Спеціальні умови</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>2 %</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 %</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 %</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 %</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6 %</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7 %</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>8 %</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10 %</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13 %</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14 %</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15 %</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GeneralPrice__c</fullName>
        <label>Сумма всіх штор</label>
        <summarizedField>Curtain__c.GeneralPrice__c</summarizedField>
        <summaryFilterItems>
            <field>Curtain__c.GeneralPrice__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Curtain__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Контакт</label>
    <nameField>
        <label>Ім&apos;я</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Контакти</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactTriggerHandler.cls
/**
 * Created by Kostiantyn_Marchenkov on 2/26/2025.
 */

public class ContactTriggerHandler {
    public static void run(List<Contact__c> newList, List<Contact__c> oldList,
            Map<Id, Contact__c> newMap, Map<Id, Contact__c> oldMap,
            Boolean isBefore, Boolean isAfter, Boolean isInsert,
            Boolean isUpdate, Boolean isDelete, Boolean isUndelete) {
        
        if (isBefore) {
            if (isInsert) beforeInsert(newList);
            if (isUpdate) beforeUpdate(newList, oldMap);
            if (isDelete) beforeDelete(oldList);
        }
        
        if (isAfter) {
            if (isInsert) afterInsert(newList);
            if (isUpdate) afterUpdate(newList, oldMap);
            if (isDelete) afterDelete(oldList);
            if (isUndelete) afterUndelete(newList);
        }
    }
    
    public static void beforeInsert(List<Contact__c> newList) {
    }
    
    public static void beforeUpdate(List<Contact__c> newList, Map<Id, Contact__c> oldMap) {
        System.debug('beforeUpdateCon');
        List<Contact__c> contacts = new List<Contact__c>();
        List<Contact__c> contactsUpdateFinalPrice = new List<Contact__c>();
        for (Contact__c contact : newList) {
            
            if(contact.GeneralPrice__c != null && contact.FinalPrice__c == null &&
                    contact.GeneralPrice__c != oldMap.get(contact.Id).GeneralPrice__c) {
                contactsUpdateFinalPrice.add(contact);
            }
        }
        
        if(!contactsUpdateFinalPrice.isEmpty()) {
            ContactTriggerHelper.updateFields(contactsUpdateFinalPrice);
        }
        
    }
    
    public static void beforeDelete(List<Contact__c> oldList) {
    }
    
    public static void afterInsert(List<Contact__c> newList) {
    }
    
    public static void afterUpdate(List<Contact__c> newList, Map<Id, Contact__c> oldMap) {
        System.debug('afterUpdateCon');
        List<Contact__c> contacts = new List<Contact__c>();
//        List<Contact__c> contactsUpdateFinalPrice = new List<Contact__c>();
        for (Contact__c contact : newList) {
            System.debug(oldMap.get(contact.Id).GeneralDiscount__c);
            if (contact.GeneralDiscount__c != oldMap.get(contact.Id).GeneralDiscount__c) {
                contacts.add(contact);
            }
            
//            if(contact.GeneralPrice__c != null && contact.FinalPrice__c == null &&
//                    contact.GeneralPrice__c != oldMap.get(contact.Id).GeneralPrice__c) {
//                contactsUpdateFinalPrice.add(contact);
//            }
        }
        System.debug(contacts);
        if (!contacts.isEmpty()) {
            System.debug('updateRelatedCurtainsDiscount');
            ContactTriggerHelper.updateRelatedCurtainsDiscount(contacts[0]);
        }
        
//        if(!contactsUpdateFinalPrice.isEmpty()) {
//            ContactTriggerHelper.updateFields(contactsUpdateFinalPrice);
//        }
    }
    
    public static void afterDelete(List<Contact__c> oldList) {
    }
    
    public static void afterUndelete(List<Contact__c> newList) {
    }
}