src/objects/Contact__c.object
<CustomObject>
    <fields>
        <fullName>FinalPrice__c</fullName>
        <inlineHelpText>Ціна, яку затверджено з покупцем в ході розгляду і затвердження замовлення.</inlineHelpText>
        <label>Фінальна ціна</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GeneralDiscount__c</fullName>
        <label>Спеціальні умови</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>2 %</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 %</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 %</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 %</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6 %</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7 %</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>8 %</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10 %</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13 %</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14 %</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15 %</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GeneralPrice__c</fullName>
        <label>Сумма всіх штор</label>
        <summarizedField>Curtain__c.GeneralPrice__c</summarizedField>
        <summaryFilterItems>
            <field>Curtain__c.GeneralPrice__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Curtain__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Контакт</label>
    <nameField>
        <label>Ім&apos;я</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Контакти</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Curtain__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Контакт</label>
        <referenceTo>Contact__c</referenceTo>
        <relationshipLabel>Curtains</relationshipLabel>
        <relationshipName>Curtains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CurtainDiscount__c</fullName>
        <label>Спеціальні умови</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>2 %</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 %</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 %</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 %</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6 %</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7 %</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>8 %</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10 %</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13 %</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14 %</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15 %</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinalPrice__c</fullName>
        <label>Загальна сумма1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeneralPrice__c</fullName>
        <label>Загальна сумма</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Штора</label>
    <nameField>
        <label>Штора Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Штори</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactTriggerHelper.cls
/**
 * Created by Kostiantyn_Marchenkov on 2/26/2025.
 */

public class ContactTriggerHelper {
    
    public static void updateRelatedCurtainsDiscount(Contact__c contact) {
        List<Curtain__c> relatedCurtains = [
                SELECT CurtainDiscount__c
                FROM Curtain__c
                WHERE Contact__c = :contact.Id
        ];
        System.debug('relatedCurtains ' + relatedCurtains);
        if (!relatedCurtains.isEmpty()) {
            for (Curtain__c curtain : relatedCurtains) {
                System.debug((String) contact.GeneralDiscount__c);
                curtain.CurtainDiscount__c = (String) contact.GeneralDiscount__c;
                System.debug(curtain.CurtainDiscount__c);
            }
        }
        System.debug('relatedCurtains 2 ' + relatedCurtains);
        Database.update(relatedCurtains);
    }
    
    public static void updateFields(List<Contact__c> contacts) {
        for (Contact__c contact : contacts) {
            contact.FinalPrice__c = contact.GeneralPrice__c;
        }
        
//        update contacts;
    }
}