src/objects/Contact__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Адреса</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientName__c</fullName>
        <label>Телефон</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Коментар</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expenses__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Витрати</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FinalPrice__c</fullName>
        <inlineHelpText>Ціна, яку затверджено з покупцем в ході розгляду і затвердження замовлення.</inlineHelpText>
        <label>Фінальна ціна</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GeneralDiscount__c</fullName>
        <label>Спеціальні умови</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>2 %</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 %</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 %</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 %</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6 %</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7 %</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>8 %</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10 %</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13 %</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14 %</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15 %</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GeneralPrice__c</fullName>
        <label>Сумма всіх штор</label>
        <summarizedField>Curtain__c.GeneralPrice__c</summarizedField>
        <summaryFilterItems>
            <field>Curtain__c.GeneralPrice__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Curtain__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SelectedCurtains__c</fullName>
        <label>Сума вибраних штор</label>
        <summarizedField>Curtain__c.GeneralPrice__c</summarizedField>
        <summaryFilterItems>
            <field>Curtain__c.Check__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Curtain__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Контакт</label>
    <nameField>
        <label>Ім&apos;я</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Контакти</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Curtain__c.object
<CustomObject>
    <fields>
        <fullName>AdvancePaymentReceived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Аванс отримано</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Carniz__c</fullName>
        <label>Карніз</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>gardinia</fullName>
                    <label>Gardinia</label>
                </value>
                <value>
                    <fullName>alutat</fullName>
                    <label>Alutat</label>
                </value>
                <value>
                    <fullName>ks</fullName>
                    <label>KS</label>
                </value>
                <value>
                    <fullName>lux</fullName>
                    <label>Lux S-M</label>
                </value>
                <value>
                    <fullName>ds</fullName>
                    <label>DS</label>
                </value>
                <value>
                    <fullName>circle</fullName>
                    <label>Круглий</label>
                </value>
                <value>
                    <fullName>metal</fullName>
                    <label>Металічний П-обр крючок</label>
                </value>
                <value>
                    <fullName>other</fullName>
                    <label>Інший</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Вибрати</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContactDiscount__c</fullName>
        <label>Знижка з контакта</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Контакт</label>
        <referenceTo>Contact__c</referenceTo>
        <relationshipLabel>Curtains</relationshipLabel>
        <relationshipName>Curtains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DeliveryNumber__c</fullName>
        <label>Кількість доставок</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery__c</fullName>
        <label>Доставка</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>120</fullName>
                    <label>120 грн.</label>
                </value>
                <value>
                    <fullName>150</fullName>
                    <label>150 грн.</label>
                </value>
                <value>
                    <fullName>180</fullName>
                    <label>180 грн.</label>
                </value>
                <value>
                    <fullName>200</fullName>
                    <label>200 грн.</label>
                </value>
                <value>
                    <fullName>220</fullName>
                    <label>220 грн.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Diameter__c</fullName>
        <label>Діаметр Карнізу</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                    <label>2 см</label>
                </value>
                <value>
                    <fullName>2_5</fullName>
                    <label>2,5 см</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 см</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinalPrice__c</fullName>
        <label>Загальна сумма1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GeneralPrice__c</fullName>
        <label>Загальна сумма</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Висота (см)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ManualPrice__c</fullName>
        <label>Відома ціна</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Назва</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriceType__c</fullName>
        <label>Валюта</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>грн</fullName>
                    <label>грн.</label>
                </value>
                <value>
                    <fullName>уо</fullName>
                    <label>опт, у.о.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Ціна тканини</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Кількість</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 штука</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 штуки</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 штуки</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <label>Кімната</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Тип</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>shtora</fullName>
                    <label>Штора</label>
                </value>
                <value>
                    <fullName>tul</fullName>
                    <label>Тюль</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Viizd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Виїзд</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zbirka__c</fullName>
        <label>Збірка</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>enigma_15</fullName>
                    <label>Enigma 1:1,5</label>
                </value>
                <value>
                    <fullName>enigma_18</fullName>
                    <label>Enigma 1:1,8</label>
                </value>
                <value>
                    <fullName>enigma_2</fullName>
                    <label>Enigma 1:2</label>
                </value>
                <value>
                    <fullName>enigma_25</fullName>
                    <label>Enigma 1:2,5</label>
                </value>
                <value>
                    <fullName>enigma_3</fullName>
                    <label>Enigma 1:3</label>
                </value>
                <value>
                    <fullName>sofora_18</fullName>
                    <label>Sofora 1:1,8</label>
                </value>
                <value>
                    <fullName>sofora_2</fullName>
                    <label>Sofora 1:2</label>
                </value>
                <value>
                    <fullName>pinella</fullName>
                    <label>Pinella</label>
                </value>
                <value>
                    <fullName>hvulya</fullName>
                    <label>Хвиля 1:2</label>
                </value>
                <value>
                    <fullName>luversna</fullName>
                    <label>Люверсна</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Штора</label>
    <nameField>
        <label>Штора Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Штори</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Curtain__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Коментар</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/classes/ContactDeepClone.cls
public with sharing class ContactDeepClone {
    
    @InvocableMethod(label='Contact Deep Clone')
    public static List<Id> contactDeepClone(List<String> recordIds) {
        // Получаем исходный контакт по ID
        List<Contact__c> contactsToClone = [
                SELECT
                        Id,
                        Name,
                        Address__c,
                        Expenses__c,
                        Description__c,
                        GeneralDiscount__c,
                        SelectedCurtains__c,
                        GeneralPrice__c,
                        ClientName__c,
                        FinalPrice__c
                FROM Contact__c
                WHERE Id = :recordIds[0]
                LIMIT 1
        ];
        
        // Генерируем новое имя для контакта
        String newName = cloneContactName(contactsToClone[0].Name);
        
        // Клонируем сам контакт (не копируем ID, копируем все поля)
        Contact__c clonedContact = contactsToClone[0].clone(false, true); // false - не копируем ID, true - копируем все поля
        clonedContact.Name = newName; // Присваиваем новому контакту имя с увеличенной приставкой
        
        // Сохраняем клонированный контакт
        insert clonedContact;
        
        // Получаем все связанные записи Assortment__c для клонированного контакта
        List<Assortment__c> assortmentsToClone = [
                SELECT Id, Name, Price__c, Size__c, Contact__c
                FROM Assortment__c
                WHERE Contact__c = :contactsToClone[0].Id
        ];
        
        // Клонируем связанные записи Assortment__c
        List<Assortment__c> clonedAssortments = new List<Assortment__c>();
        for (Assortment__c assortment : assortmentsToClone) {
            Assortment__c clonedAssortment = assortment.clone(false, true); // false - не копируем ID, true - копируем все поля
            clonedAssortment.Contact__c = clonedContact.Id; // Привязываем к новому контакту
            clonedAssortments.add(clonedAssortment);
        }
        
        // Сохраняем клонированные ассортименты
        if (!clonedAssortments.isEmpty()) {
            insert clonedAssortments;
        }
        
        // Получаем все связанные записи Curtain__c для клонированного контакта
        List<Curtain__c> curtainsToClone = [
                SELECT
                        Id,
                        Name,
                        CreatedById,
                        LastModifiedById,
                        AdvancePaymentReceived__c,
                        PriceType__c,
                        Check__c,
                        Height__c,
                        Viizd__c,
                        ManualPrice__c,
                        Delivery__c,
                        Diameter__c,
                        GeneralPrice__c,
                        FinalPrice__c,
                        Zbirka__c,
                        ContactDiscount__c,
                        Carniz__c,
                        Description__c,
                        Contact__c,
                        Quantity__c,
                        DeliveryNumber__c,
                        Room__c,
                        MeterageNaPoshiv__c,
                        TasmaMetrage__c,
                        Meterage__c,
                        Navis__c,
                        Name__c,
                        Nisha__c,
                        ObrobkaNiz__c,
                        PostpaidReceived__c,
                        TasmaPlace__c,
                        CurtainDiscount__c,
                        Status__c,
                        Tasma__c,
                        Type__c,
                        CurtainPaid__c,
                        HeightPoint__c,
                        PicturesAttached__c,
                        NavisPriceSum__c,
                        PoshivPriceSum__c,
                        TasmaPriceSum__c,
                        CurtainPriceSum__c,
                        NavisPrice__c,
                        PoshivPrice__c,
                        TasmaPrice__c,
                        Price__c,
                        CarnizWigth__c,
                        CustomWigth__c,
                        ContactName__c
                FROM Curtain__c
                WHERE Contact__c = :contactsToClone[0].Id
        ];
        
        
        // Клонируем связанные записи Curtain__c
        List<Curtain__c> clonedCurtains = new List<Curtain__c>();
        
        for (Curtain__c curtain : curtainsToClone) {
            String newCurtainName = cloneContactName(curtain.Room__c);
            Curtain__c clonedCurtain = curtain.clone(false, true); // false - не копируем ID, true - копируем все поля
            clonedCurtain.Contact__c = clonedContact.Id; // Привязываем к новому контакту
            clonedCurtain.Room__c = newCurtainName; // Привязываем к новому контакту
            clonedCurtains.add(clonedCurtain);
        }
        
        // Сохраняем клонированные занавески
        if (!clonedCurtains.isEmpty()) {
            insert clonedCurtains;
        }
        
        // Возвращаем ID нового контакта в список
        return new List<Id>{clonedContact.Id};
    }
    
    // Метод для генерации имени нового контакта
    private static String cloneContactName(String originalName) {
        // Проверяем, есть ли уже приставка "Пропозиція" в имени
        Integer index = originalName.indexOf('Пропозиція');
        if (index != -1) {
            // Если есть, увеличиваем номер
            Integer proposalNumber = Integer.valueOf(originalName.substring(index + 11).trim()) + 1;
            return originalName.substring(0, index) + 'Пропозиція ' + proposalNumber;
        } else {
            // Если нет, добавляем "Пропозиція 2"
            return originalName + ' Пропозиція 2';
        }
    }
}