src/objects/Curtain__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Тип</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>shtora</fullName>
                    <label>Штора</label>
                </value>
                <value>
                    <fullName>tul</fullName>
                    <label>Тюль</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Штора</label>
    <nameField>
        <label>Штора Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Штори</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CurtainTriggerHelper.cls
/**
 * Created by Kostiantyn_Marchenkov on 2/25/2025.
 */

public class CurtainTriggerHelper{
    public static void recalculateFields(Curtain__c curtainObject) {
        System.debug('recalculateFields');
        CurtainCalculator.calculateData(curtainObject);
    }
    
    public static void populateFields(List<Curtain__c> curtains) {
        Schema.DescribeFieldResult fieldDesc = Curtain__c.Type__c.getDescribe();
        Map<String, String> picklistMap = new Map<String, String>();
        
        for (Schema.PicklistEntry entry : fieldDesc.getPicklistValues()) {
            picklistMap.put(entry.getValue(), entry.getLabel());
        }
        
        for (Curtain__c curt : curtains) {
            if (picklistMap.containsKey(curt.Type__c)) {
                curt.Name = picklistMap.get(curt.Type__c);
            }
        }
    }

}